### ISSUE TITLE
Add missing fields

### ISSUE THREAD

**Issue by johnrix** [realexpayments/rxp-hpp-php#2]
Please add the following missing fields to the HppResponse object:

CARD_PAYMENT_BUTTON
MERCHANT_RESPONSE_URL
HPP_LANG
SHIPPING_CODE
SHIPPING_CO
BILLING_CODE
BILLING_CO

**Comment by johnrix** [comment]
Never mind. Can see they are accessible via getSupplementaryData method

**Comment by seanmacdomhnall** [comment]
Thanks for the feedback. We'll add specific methods in the next release.

Seán MacDomhnall
**Realex Payments**
